### ISSUE TITLE
Using existing images from the cloud

### ISSUE THREAD

**Issue by mgariepy** [busterswt/MNAIOv2#2]
Using already available images from the cloud you are deploying on would be useful, and would save some time in uploading.

**Comment by busterswt** [comment]
Noted. I originally had this in place, but thought a "self contained" approach might be cleaner. I'll see what I can do here.

**Comment by busterswt** [comment]
Got it, thanks! I have implemented a new env var to solve this:

export MNAIO_OSA_VM_IMAGE_UUID=<Glance Image UUID>

This will override MNAIO_OSA_VM_IMAGE, which defaults to focal and downloads the current Ubuntu image.

Next up: flavors. That will come in a few days.
