### ISSUE TITLE
Vars files missing?

### ISSUE THREAD

**Issue by bjoernt** [busterswt/MNAIOv2#4]
It seems the following vars files are referenced but missing

```
ERROR! vars file defaults/main.yml was not found

ERROR! vars file vars/terraform.yml was not found
```

**Comment by busterswt** [comment]
Thanks - this should be fixed now. I'll be converting this to a role at some point, but for now the vars are all being included as vars_files

**Comment by bjoernt** [comment]
@busterswt  vars/terraform.yml is also referenced but not present/created inside playbooks such as pre-deploy-rpc.yml, bootstrap-vms.yml

**Comment by busterswt** [comment]
Yes - it is auto-generated by create-terraform:

./create-terraform.yml:43:        - { src: 'tf/101-ansible-vars.tf.j2', dest: '101-ansible-vars.tf' }

./templates/tf/101-ansible-vars.tf.j2:29:  filename = "${path.module}/../playbooks/vars/terraform.yml"

Should be OK now, but let me know.
